### ISSUE TITLE
Homepage: Admin can't organize artists in a specific order

### ISSUE THREAD

**Issue by bogreudell** [merciba/lavarecords_lavatheme#2]

**Comment by merciba** [comment]
Background: 

This is normally achieved using the Post Order plugin which is installed and working already on staging - Tours & Events, Playlist, and even Posts menus show the 'Re-Order' menu below their sidebar labels. 

However, something is preventing the Artists menu from showing the appropriate 'Re-Order' menu like all the others.

I've been banging my head against the wall trying to figure this out, it must be a db thing, possibly related to the way the Custom Post Types UI works.

**Comment by merciba** [comment]
Fixed by changing a conflicting setting on the 'Artists' custom post type. CMS-side should be seeing the re-order option in the menu below 'Artists' in the sidebar.
